#!/bin/bash

Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
Yellow='\033[1;33m'
White='\033[1;37m'
NC='\033[0m'
###############################################
TMP_SCRIPT=$(mktemp /tmp/countdown_script.XXXXXX)
cat << 'EOL' > "$TMP_SCRIPT"
###############################################
clear
tput cup 0 0
tput civis
# Initialize a variable to store user input
user_input=""
abc=$(echo -e "${Green}Enter text")
bcd=$(echo -e "${Cyan}(Enter only to finish):")
cde=$(echo -e "${Yellow}>>>${Purple}")
# Continue prompting for input until Enter is pressed without entering any other text
	counter=1
source /home/batan/yt-dlp/bin/activate
	while true; do
    # Move the cursor to the beginning of the line and clear it
    # Prompt for user input and store it in a temporary variable
    read -p "$abc $bcd $cde $counter  " -e input
	tput cup 0 0
	tput el
	tput cup 0 0
	tput el
	echo $input >> /home/batan/Music/temp.txt
tput cup 1 0
	(( counter++ ))
    # Check if the user pressed Enter without entering any other text
    if [ -z "$input" ]; then
        break
    fi

    # Concatenate user input to the variable
    user_input="${user_input}${input} "
done

# Move to the next line before echoing the stored variable
echo ""

# Echo the stored variable

if [[ -f /usr/bin/yt-dlp ]]; then
/usr/bin/yt-dlp -x --audio-format mp3 --download-archive /home/batan/Music/archive_vid.wiki -o /home/batan/Music/"%(title)s.%(ext)s" $user_input
else
/home/batan/.local/bin/yt-dlp -x --audio-format mp3 --download-archive /home/batan/Music/archive_vid.wiki -o /home/batan/Music/"%(title)s.%(ext)s" $user_input
fi
exit


EOL
/usr/bin/xfce4-terminal --zoom=+2 --color-text=Black --color-bg=Cyan --hide-menubar --hide-scrollbar --hide-borders --geometry="100x1+200+200" -e "sudo -u batan bash $TMP_SCRIPT" & exit




