#!/bin/bash
#############################################################
Black='\033[0;30m'
Red='\033[0;31m'
Green='\033[0;32m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Cyan='\033[0;36m'
Yellow='\033[1;33m'
White='\033[1;37m'

###   IN case the google calendar and google tasknote credentials were removed from cache ###################################
if [[ -d /home/batan/.cache/calendar.vim/ ]]; then
	echo -e "\033[41mcalendar.vim directory exists\033[0m"
exit
fi
mkdir -p /home/batan/.cache/calendar.vim/
	cp /home/batan/dot/credentials.vim /home/batan/.cache/calendar.vim/credentials.vim
###   BIND Esc to CapsLock and bind LeftCtrl to CapsLock as well ######################
/usr/bin/lc-caps
xmodmap -e "clear lock"
xmodmap -e "remove Control = Control_L"
xmodmap -e "keycode 66 = Control_L"
xmodmap -e "add Control = Control_L"
xcape -e "Control_L=Escape"

###   EXPORTING LC-FZF-layout   ########################################################

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
 --color=fg:#195190,bg:#121212,hl:#788a9c
 --color=fg+:#cccccc,bg+:#195190,hl+:#99c2ff
 --color=info:#d9b309,prompt:#b83737,pointer:#af5fff
 --color=marker:#ffe87f,spinner:#af5fff,header:#b83737'


